### ISSUE TITLE
Update to latest version

### ISSUE THREAD

**Issue by rashadgasimli** [flathub/dev.zed.Zed#16]
The latest version fixes GPU detection

**Comment by jerome-benoit** [comment]
@ShobuPrime, @tomaswarynyca: is possible consider automating the version upgrade process with flathubbot? 

That would lessen the maintainer(s) workload.

**Comment by tomaswarynyca** [comment]
Yes, that's my idea and that's why I fixed the config in #15 to make flathubbot work.

**Comment by ShobuPrime** [comment]
> @ShobuPrime, @tomaswarynyca: is it possible to consider automating the version upgrade process with flathubbot?
> 
> That would lessen the maintainer(s) workload.

When I originally created the Flatpak, I did submit a flathub.json which was intended to do just that with the `"automerge-flathubbot-prs": true` properties, but [apparently they aren't allowed anymore](https://github.com/flathub/dev.zed.Zed/pull/15#issuecomment-2351622296)

**Comment by ShobuPrime** [comment]
If we're allowed to use a Github action to check the hashes and version upgrades, I would be for that being developed.

**Comment by tomaswarynyca** [comment]
We don't need any github action, flathubbot will be the job to check if there is a new version and generate the PR - just wait until Wednesday when Zed has a version and once the test build is completed, merge it. 👍🏻 

@rashadgasimli the latest version will be available in the next few hours - thanks @ShobuPrime.

**Comment by rashadgasimli** [comment]
@tomaswarynyca thanks
