### ISSUE TITLE
Use SDK with zed with escape option off

### ISSUE THREAD

**Issue by baronleonardo** [flathub/dev.zed.Zed#6]
I used this env `ZED_FLATPAK_NO_ESCAPE=1` and `FLATPAK_ENABLE_SDK_EXT=llvm15`, but the later was never recognized (the terminal doesn't see clang at all)

**Comment by appelgriebsch** [comment]
I think we need a startup script that enables the SDK similar to this: https://github.com/Lctrs/jetbrains-flatpak-wrapper/blob/master/jetbrains.sh#L51-L74

**Comment by baronleonardo** [comment]
I don't want to use anything from my host
I want to use the SDKs from flatpak

**Comment by jerome-benoit** [comment]
What is the detailed rationale for that usage?

**Comment by baronleonardo** [comment]
hmmm,
that's how I develop, and that how I keep my system clean
all the tools I need is withing flatpak, whatever it is a binary or sdk
if I need an extra library, I simply compile it

**Comment by jerome-benoit** [comment]
It's a somewhat light rationale for a change that introduce serious downsides to the zed flatpak behavior (cf. follow up PR comments) by using existing tools ;-). Even if done without introducing breaking change. A proper integration would require to make a lighter zed dedicated wrapper.

**Comment by jerome-benoit** [comment]
I doubt the maintainer will accept the PR with the current issues raised during testing (as a maintainer, I'll not). Integration is still doable but will need to implement a dedicated shell wrapper, and I do not have that time at the moment.
